# actions/upload-artifact@v3 으로 하니깐 오류 발생
# actions/upload-artifact@v4 로 변경하니 오류 해결
name: artifact
on: push

jobs:
    upload-artifact:
        runs-on: ubuntu-latest
        steps:
        - name: echo
          run: echo hello-world > hello.txt
        - name: upload artifact
          uses: actions/upload-artifact@v4
          with:
            name: artifact-test
            path: ./hello.txt

    download-artifact:
        runs-on: ubuntu-latest
        needs: [upload-artifact]
        steps:
        - name: download artifact
          uses: actions/download-artifact@v4
          with:
            name: artifact-test
            path: ./
        - name: check
          run: cat hello.txt