# 한 job에서 생성된 데이터.
# 동일한 job의 step, 다른 job 데이터 공유 가능

name: output
on: push

jobs:
    create-output:
        runs-on: ubuntu-latest
        outputs:
            test: ${{ steps.check-output.outputs.test }}
        steps:
        - name: echo output
          id: check-output
          run: |
            echo "test=hello" >> $GITHUB_OUTPUT
        - name: check output
          run: |
            echo ${{ steps.check-output.outputs.test }}

    get-output:
        needs: [create-output]
        runs-on: ubuntu-latest
        steps:
        - name: get output
          run: echo ${{ needs.create-output.outputs.test }}